import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FloatingNav from "@/components/navbar";
import Footer from "@/components/footer";
import { Poppins } from 'next/font/google'
import { Analytics } from "@vercel/analytics/next"

const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['400', '600'], // Choose weights you need
  style: ['normal', 'italic'], // Optional styles
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Vikram's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <FloatingNav/>
        {children}
         <Analytics />
        <Footer/>
      </body>
    </html>
  );
}
